### ISSUE TITLE
Error “Schema mismatch for input column 'DescriptionFeaturized_CharExtractor'” on Input Text Very Long 

### ISSUE THREAD

**Issue by robinhoo1973** [wietsesas/PowerML#1]
I'm trying to train a model by inputting the very long texts as the text features, and when I came to command Build-MLModel, I also got the below error:

_Line | 44 |  $model = $pipeline | Build-MLModel -Data $data
     |                       ~~~~~~~~~~~~~~~~~~~~~~~~~
     | Schema mismatch for input column 'DescriptionFeaturized_CharExtractor': expected Expected known-size   
     | vector of Single, got Vector<Single> (Parameter 'inputSchema')_

I have included my source code below for you to look over.

`
$modelPath = Join-Path -Path $PSScriptRoot -ChildPath "model"
$dataPath = Join-Path -Path $PSScriptRoot -ChildPath "data"

@{
Name = "VulnerabilityAction"
Properties = @{
Id = @{ Type = "string" ; LoadColumn = 0 }
Severity = @{ Type = "string" ; LoadColumn = 1 }
Title = @{ Type = "string" ; LoadColumn = 4 }
Description = @{ Type = "string" ; LoadColumn = 5 }
Solution = @{ Type = "string" ; LoadColumn = 6 }
Action = @{ Type = "string" ; LoadColumn = 7 }
}
} | ConvertTo-Json | Out-File -FilePath "$modelPath\VulnerabilityAction.json"

@{
Name = "ActionPrediction"
Properties = @{
Id = @{ Type = "string" }
Severity = @{ Type = "string" }
Title = @{ Type = "string" }
Description = @{ Type = "string" }
Solution = @{ Type = "string" }
Action = @{ Type = "string" ; ColumnName = "PredictedLabel" }
}
} | ConvertTo-Json | Out-File -FilePath "$modelPath\ActionPrediction.json"

Register-MLType "$modelPath\VulnerabilityAction.json"
Register-MLType "$modelPath\ActionPrediction.json"

$data = Import-MLData -Type VulnerabilityAction -Path "$dataPath\actions_train.tsv" -HasHeader

$pipeline = Add-MapValueToKeyTransform -OutputColumn "Label" -InputColumn "Action" |
Add-FeaturizeTextTransform -OutputColumn "IdFeaturized" -InputColumn "Id" |
Add-FeaturizeTextTransform -OutputColumn "SeverityFeaturized" -InputColumn "Severity" |
Add-FeaturizeTextTransform -OutputColumn "TitleFeaturized" -InputColumn "Title" |
Add-FeaturizeTextTransform -OutputColumn "DescriptionFeaturized" -InputColumn "Description" |
Add-FeaturizeTextTransform -OutputColumn "SolutionFeaturized" -InputColumn "Solution" |
Add-ConcatenateTransform -OutputColumn "Features" -InputColumns "IdFeaturized","SeverityFeaturized","TitleFeaturized", "DescriptionFeaturized","SolutionFeaturized"|
Add-CacheCheckpoint |
Add-SdcaMaximumEntropyMulticlassTrainer |
Add-MapKeyToValueTransform -OutputColumn "PredictedLabel"

$model = $pipeline | Build-MLModel -Data $data
Export-MLModel -Model $model -Path "$modelPath\model.zip" -Schema $data.Schema -Force
`

**Comment by wietsesas** [comment]
Can you provide me (a sample of) the input data for testing?

**Comment by robinhoo1973** [comment]
> Can you provide me (a sample of) the input data for testing?

I found the problem: The LoadColumn order had an issue, as I accidentally deleted some columns. Now I corrected the loadcolumn sequence number. now issue. now. Thanks for the great work to port it for PowerShell.

**Comment by wietsesas** [comment]
You're welcome, thx for the feedback!
